* org-table-xtras

  This emacs minor mode adds some extra functionality to org-mode tables. 

  To use, put the .el file in your load path, along with 

#+BEGIN_SRC 
(require 'org-table-xtras)
#+END_SRC

  Then issue

#+BEGIN_SRC 
M-x org-table-xtras
#+END_SRC

** Copying Formulas

   If you want to use a lot of field formulas, it's time consuming to copy the formulas into subsequent cells. This minor mode includes commands that will make this quicker.

#+BEGIN_SRC 
C-c C-= C-n : org-table-xtras-copy-field-next-row
#+END_SRC

  This shortcut copies a field formula into the next row. A prefix argument copies the field formula into multiple rows. A negative prefix argument copies the field formula up. 
  
#+BEGIN_SRC 
C-c C-= C-f : org-table-xtras-copy-field-next-column
#+END_SRC

  Similarly, but with columns.

#+BEGIN_SRC 
C-c C-= C-d : org-table-xtras-copy-field-diagonally
#+END_SRC

  Similarly, but diagonally through the spreadsheet.

** Exporting formulas

   My biggest pet peeve with excel is that you can't quickly visualize all of the formulas going on in the spreadsheet at once. In order to get this functionality in org-mode, I defined a function that will add footnote references to all cells that have a formula. Cells with identical formulas reference the same footnote. 

These two functions add and remove these footnotes from the table:

#+BEGIN_SRC 
C-c C-= C-p : org-table-xtras-print-formulas
C-c C-= C-r : org-table-xtras-remove-fns
#+END_SRC

Note that these functions require the table to be named.

However, it's can also be convenient to handle the footnote generation at the export stage. In order to do this, add the following code to your .emacs:

#+BEGIN_SRC 
(add-hook 'org-export-before-parsing-hook 'org-table-xtras-export-hook)
#+END_SRC

This creates the footnotes before exporting for all named tables.

  See [[example.org]] for an example. This org-file generates [[example.pdf]].

** Spreadsheets as functions
   I also wrote a function, org-table-xtras-eval-table, that returns the value of a parameter from a spreadsheet given alternative values for some given parameters. This is analagous to excel's "Scenario Manager" functionality, but it treats each spreadsheet as a fully autonomous function. For example, [[example2.org]] includes a primitive DCF spreadsheet that takes a number of parameters (cost of equity, growth rates, etc.) as arguments. You can then see what the DCF would return under different COE values in the second table, where org-table-xtras is called for different values. The results are shown in [[example2.pdf]]
