* org-table-xtras

  This emacs minor mode adds some extra functionality to org-mode tables. It's a bit hacked together at the moment. Note that it edits some variables, such as *org-latex-tables-centered* and *org-calc-default-modes*.

  To use, just put the .el file in your load-path and load the minor mode via 

#+BEGIN_SRC 
M-x org-table-xtras
#+END_SRC

  This minor mode includes the following commands:

#+BEGIN_SRC 
C-c C-= C-n : org-table-xtras-copy-field-next-row
#+END_SRC

  This shortcut copies a field formula into the next row. A prefix argument copies the field formula into multiple rows. A negative prefix argument copies the field formula up. 
  
#+BEGIN_SRC 
C-c C-= C-f : org-table-xtras-copy-field-next-column
#+END_SRC

  Similarly, but with columns.

#+BEGIN_SRC 
C-c C-= C-d : org-table-xtras-copy-field-diagonally
#+END_SRC

  Similarly, but diagonally through the spreadsheet.

#+BEGIN_SRC 
C-c C-= C-p : org-table-xtras-print-formulas
#+END_SRC

  This adds formulas in a *tablenotes* environment below the table, and adds reference footnotes to the relevant table cells. If you'd like to edit the table after including the reference footnotes, C-u C-u C-c C-* will recalculate the table.


  See [[example.org]] for an example. This org-file generates [[example.pdf]].

** Spreadsheets as functions
   I also wrote a function, org-table-xtras-eval-table, that returns the value of a parameter from a spreadsheet given alternative values for some given parameters. This is analagous to excel's "Scenario Manager" functionality, but it treats each spreadsheet as a fully autonomous function. For example, [[example2.org]] includes a primitive DCF spreadsheet that takes a number of parameters (cost of equity, growth rates, etc.) as arguments. You can then see what the DCF would return under different COE values in the second table, where org-table-xtras is called for different values.
